// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"


// COMPONENT SIDEBAR

lv_obj_t *ui_SIDEBAR_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_SIDEBAR;
cui_SIDEBAR = lv_obj_create(comp_parent);
lv_obj_set_width( cui_SIDEBAR, lv_pct(20));
lv_obj_set_height( cui_SIDEBAR, lv_pct(100));
lv_obj_set_x( cui_SIDEBAR, -308 );
lv_obj_set_y( cui_SIDEBAR, -2 );
lv_obj_set_align( cui_SIDEBAR, LV_ALIGN_CENTER );
lv_obj_clear_flag( cui_SIDEBAR, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_SIDEBAR_NUM);
children[UI_COMP_SIDEBAR_SIDEBAR] = cui_SIDEBAR;
lv_obj_add_event_cb(cui_SIDEBAR, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_SIDEBAR, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_SIDEBAR_create_hook(cui_SIDEBAR);
return cui_SIDEBAR; 
}

