// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: ui

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void screen2relay1(lv_event_t * e);
void screen2relay2(lv_event_t * e);
void screen2relay3(lv_event_t * e);
void screen2relay4(lv_event_t * e);
void screen2relay5(lv_event_t * e);
void screen2relay6(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
