// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: ui

#include "ui.h"

void ui_Screen3_screen_init(void)
{
ui_Screen3 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_flex_flow(ui_Screen3,LV_FLEX_FLOW_COLUMN_WRAP);
lv_obj_set_flex_align(ui_Screen3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

ui_Panel13 = lv_obj_create(ui_Screen3);
lv_obj_set_width( ui_Panel13, lv_pct(18));
lv_obj_set_height( ui_Panel13, lv_pct(100));
lv_obj_set_x( ui_Panel13, -294 );
lv_obj_set_y( ui_Panel13, 13 );
lv_obj_set_align( ui_Panel13, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel13,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_Panel13, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Panel13, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel13, lv_color_hex(0x81C27E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel13, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel14 = lv_obj_create(ui_Panel13);
lv_obj_set_width( ui_Panel14, lv_pct(120));
lv_obj_set_height( ui_Panel14, lv_pct(10));
lv_obj_set_x( ui_Panel14, -412 );
lv_obj_set_y( ui_Panel14, -182 );
lv_obj_set_align( ui_Panel14, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel14, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label9 = lv_label_create(ui_Panel14);
lv_obj_set_width( ui_Label9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label9, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label9,"MENU");
lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel15 = lv_obj_create(ui_Panel13);
lv_obj_set_width( ui_Panel15, lv_pct(120));
lv_obj_set_height( ui_Panel15, lv_pct(30));
lv_obj_set_x( ui_Panel15, -337 );
lv_obj_set_y( ui_Panel15, -75 );
lv_obj_set_align( ui_Panel15, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel15,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_Panel15, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Panel15, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label10 = lv_label_create(ui_Panel15);
lv_obj_set_width( ui_Label10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label10, -328 );
lv_obj_set_y( ui_Label10, -135 );
lv_obj_set_align( ui_Label10, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label10,"HOME");

ui_ImgButton7 = lv_imgbtn_create(ui_Panel15);
lv_imgbtn_set_src(ui_ImgButton7, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_home_png, NULL);
lv_obj_set_height( ui_ImgButton7, 64);
lv_obj_set_width( ui_ImgButton7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_align( ui_ImgButton7, LV_ALIGN_CENTER );

ui_Panel16 = lv_obj_create(ui_Panel13);
lv_obj_set_width( ui_Panel16, lv_pct(120));
lv_obj_set_height( ui_Panel16, lv_pct(30));
lv_obj_set_align( ui_Panel16, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel16,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_Panel16, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Panel16, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label11 = lv_label_create(ui_Panel16);
lv_obj_set_width( ui_Label11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label11, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Label11,"RELAY");

ui_ImgButton8 = lv_imgbtn_create(ui_Panel16);
lv_imgbtn_set_src(ui_ImgButton8, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_toggle_png, NULL);
lv_obj_set_height( ui_ImgButton8, 64);
lv_obj_set_width( ui_ImgButton8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_align( ui_ImgButton8, LV_ALIGN_CENTER );

ui_Panel17 = lv_obj_create(ui_Panel13);
lv_obj_set_width( ui_Panel17, lv_pct(120));
lv_obj_set_height( ui_Panel17, lv_pct(30));
lv_obj_set_align( ui_Panel17, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel17,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_Panel17, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Panel17, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label12 = lv_label_create(ui_Panel17);
lv_obj_set_width( ui_Label12, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label12, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label12, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label12,"SCHEDULE");

ui_ImgButton9 = lv_imgbtn_create(ui_Panel17);
lv_imgbtn_set_src(ui_ImgButton9, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_schedule_png, NULL);
lv_obj_set_height( ui_ImgButton9, lv_pct(80));
lv_obj_set_width( ui_ImgButton9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_align( ui_ImgButton9, LV_ALIGN_CENTER );

ui_Panel18 = lv_obj_create(ui_Screen3);
lv_obj_set_width( ui_Panel18, lv_pct(80));
lv_obj_set_height( ui_Panel18, lv_pct(100));
lv_obj_set_x( ui_Panel18, -51 );
lv_obj_set_y( ui_Panel18, -16 );
lv_obj_set_align( ui_Panel18, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel18, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel18, lv_color_hex(0x81C27E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel18, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_ImgButton7, ui_event_ImgButton7, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Panel15, ui_event_Panel15, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ImgButton8, ui_event_ImgButton8, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Panel16, ui_event_Panel16, LV_EVENT_ALL, NULL);

}
