// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: ui

#include "ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_flex_flow(ui_Screen1,LV_FLEX_FLOW_COLUMN_WRAP);
lv_obj_set_flex_align(ui_Screen1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

ui_Panel1 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel1, lv_pct(18));
lv_obj_set_height( ui_Panel1, lv_pct(100));
lv_obj_set_x( ui_Panel1, -294 );
lv_obj_set_y( ui_Panel1, 13 );
lv_obj_set_align( ui_Panel1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel1,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_Panel1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Panel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x81C27E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel3 = lv_obj_create(ui_Panel1);
lv_obj_set_width( ui_Panel3, lv_pct(120));
lv_obj_set_height( ui_Panel3, lv_pct(10));
lv_obj_set_x( ui_Panel3, -412 );
lv_obj_set_y( ui_Panel3, -182 );
lv_obj_set_align( ui_Panel3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label1 = lv_label_create(ui_Panel3);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"MENU");
lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel4 = lv_obj_create(ui_Panel1);
lv_obj_set_width( ui_Panel4, lv_pct(120));
lv_obj_set_height( ui_Panel4, lv_pct(30));
lv_obj_set_x( ui_Panel4, -337 );
lv_obj_set_y( ui_Panel4, -75 );
lv_obj_set_align( ui_Panel4, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel4,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_Panel4, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Panel4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label2 = lv_label_create(ui_Panel4);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, -328 );
lv_obj_set_y( ui_Label2, -135 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"HOME");

ui_ImgButton2 = lv_imgbtn_create(ui_Panel4);
lv_imgbtn_set_src(ui_ImgButton2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_home_png, NULL);
lv_obj_set_height( ui_ImgButton2, 64);
lv_obj_set_width( ui_ImgButton2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_align( ui_ImgButton2, LV_ALIGN_CENTER );

ui_Panel5 = lv_obj_create(ui_Panel1);
lv_obj_set_width( ui_Panel5, lv_pct(120));
lv_obj_set_height( ui_Panel5, lv_pct(30));
lv_obj_set_align( ui_Panel5, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel5,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_Panel5, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Panel5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label3 = lv_label_create(ui_Panel5);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label3, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Label3,"RELAY");

ui_ImgButton3 = lv_imgbtn_create(ui_Panel5);
lv_imgbtn_set_src(ui_ImgButton3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_toggle_png, NULL);
lv_obj_set_height( ui_ImgButton3, 64);
lv_obj_set_width( ui_ImgButton3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_align( ui_ImgButton3, LV_ALIGN_CENTER );

ui_Panel6 = lv_obj_create(ui_Panel1);
lv_obj_set_width( ui_Panel6, lv_pct(120));
lv_obj_set_height( ui_Panel6, lv_pct(30));
lv_obj_set_align( ui_Panel6, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel6,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_Panel6, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Panel6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label4 = lv_label_create(ui_Panel6);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"SCHEDULE");

ui_ImgButton4 = lv_imgbtn_create(ui_Panel6);
lv_imgbtn_set_src(ui_ImgButton4, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_schedule_png, NULL);
lv_obj_set_height( ui_ImgButton4, lv_pct(80));
lv_obj_set_width( ui_ImgButton4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_align( ui_ImgButton4, LV_ALIGN_CENTER );

ui_Panel2 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel2, lv_pct(80));
lv_obj_set_height( ui_Panel2, lv_pct(100));
lv_obj_set_x( ui_Panel2, -51 );
lv_obj_set_y( ui_Panel2, -16 );
lv_obj_set_align( ui_Panel2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel2,LV_FLEX_FLOW_COLUMN_WRAP);
lv_obj_set_flex_align(ui_Panel2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Panel2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x81C27E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel25 = lv_obj_create(ui_Panel2);
lv_obj_set_width( ui_Panel25, lv_pct(100));
lv_obj_set_height( ui_Panel25, lv_pct(40));
lv_obj_set_align( ui_Panel25, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel25,LV_FLEX_FLOW_COLUMN_WRAP);
lv_obj_set_flex_align(ui_Panel25, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Panel25, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel27 = lv_obj_create(ui_Panel25);
lv_obj_set_width( ui_Panel27, lv_pct(50));
lv_obj_set_height( ui_Panel27, lv_pct(100));
lv_obj_set_align( ui_Panel27, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel27,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_Panel27, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Panel27, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel27, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel27, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image1 = lv_img_create(ui_Panel27);
lv_img_set_src(ui_Image1, &ui_img_gauge_png);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label19 = lv_label_create(ui_Image1);
lv_obj_set_width( ui_Label19, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label19, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label19, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label19,"0,0");

ui_Panel28 = lv_obj_create(ui_Panel25);
lv_obj_set_width( ui_Panel28, lv_pct(50));
lv_obj_set_height( ui_Panel28, lv_pct(100));
lv_obj_set_align( ui_Panel28, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel28,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_Panel28, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Panel28, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image2 = lv_img_create(ui_Panel28);
lv_img_set_src(ui_Image2, &ui_img_gauge_png);
lv_obj_set_width( ui_Image2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Image2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label20 = lv_label_create(ui_Image2);
lv_obj_set_width( ui_Label20, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label20, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label20, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label20,"0,0");

ui_Panel26 = lv_obj_create(ui_Panel2);
lv_obj_set_width( ui_Panel26, lv_pct(100));
lv_obj_set_height( ui_Panel26, lv_pct(50));
lv_obj_set_align( ui_Panel26, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel26,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_Panel26, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Panel26, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel29 = lv_obj_create(ui_Panel26);
lv_obj_set_width( ui_Panel29, lv_pct(30));
lv_obj_set_height( ui_Panel29, lv_pct(50));
lv_obj_set_align( ui_Panel29, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel29, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label21 = lv_label_create(ui_Panel29);
lv_obj_set_width( ui_Label21, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label21, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label21, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label21,"RELAY 1");
lv_obj_set_style_text_font(ui_Label21, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel30 = lv_obj_create(ui_Panel26);
lv_obj_set_width( ui_Panel30, lv_pct(30));
lv_obj_set_height( ui_Panel30, lv_pct(50));
lv_obj_set_align( ui_Panel30, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel30, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label22 = lv_label_create(ui_Panel30);
lv_obj_set_width( ui_Label22, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label22, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label22, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label22,"RELAY 2");
lv_obj_set_style_text_font(ui_Label22, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel31 = lv_obj_create(ui_Panel26);
lv_obj_set_width( ui_Panel31, lv_pct(30));
lv_obj_set_height( ui_Panel31, lv_pct(50));
lv_obj_set_align( ui_Panel31, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel31, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label24 = lv_label_create(ui_Panel31);
lv_obj_set_width( ui_Label24, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label24, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label24, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label24,"RELAY 3");
lv_obj_set_style_text_font(ui_Label24, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel32 = lv_obj_create(ui_Panel26);
lv_obj_set_width( ui_Panel32, lv_pct(30));
lv_obj_set_height( ui_Panel32, lv_pct(50));
lv_obj_set_align( ui_Panel32, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel32, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label25 = lv_label_create(ui_Panel32);
lv_obj_set_width( ui_Label25, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label25, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label25, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label25,"RELAY 4");
lv_obj_set_style_text_font(ui_Label25, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel33 = lv_obj_create(ui_Panel26);
lv_obj_set_width( ui_Panel33, lv_pct(30));
lv_obj_set_height( ui_Panel33, lv_pct(50));
lv_obj_set_align( ui_Panel33, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel33, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label26 = lv_label_create(ui_Panel33);
lv_obj_set_width( ui_Label26, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label26, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label26, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label26,"RELAY 5");
lv_obj_set_style_text_font(ui_Label26, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel34 = lv_obj_create(ui_Panel26);
lv_obj_set_width( ui_Panel34, lv_pct(30));
lv_obj_set_height( ui_Panel34, lv_pct(50));
lv_obj_set_align( ui_Panel34, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel34, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label27 = lv_label_create(ui_Panel34);
lv_obj_set_width( ui_Label27, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label27, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label27, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label27,"RELAY 6");
lv_obj_set_style_text_font(ui_Label27, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_ImgButton3, ui_event_ImgButton3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Panel5, ui_event_Panel5, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ImgButton4, ui_event_ImgButton4, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Panel6, ui_event_Panel6, LV_EVENT_ALL, NULL);

}
